### ISSUE TITLE
BuildConfig is always null on iOS

### ISSUE THREAD

**Issue by msanchez-eutech** [ismaeldcom/react-native-build-config#10]
Autolinking is working properly, on Android i do have the gradle config that is shown but for ios BuildConfig returns a null object.

```
import BuildConfig from 'react-native-build-config';
....
// In render
console.log('BUILD CONFIG', BuildConfig);
```

Output:
```
'BUILD CONFIG', null
```

ios version: 13.2
xcode version: 11.2 beta (11B41)

**Comment by maddijoyce** [comment]
Hi @msanchez-eutech, it could possibly have something to do with your transpiler settings?
What happens if you use?
```
import * as BuildConfig from 'react-native-build-config';
```
or
```
const BuildConfig = require('react-native-build-config');
```

**Comment by cagataykapuagasi** [comment]
Same issue

**Comment by dumbre-prasad** [comment]
Hii any updates on this i am getting null aswell
