### ISSUE TITLE
It is possible to modify Info.plist file?

### ISSUE THREAD

**Issue by jullienfall** [ismaeldcom/react-native-build-config#13]
Hello. Is it possible to modify Info.plist file with this module? When Im changing some key and then console.log it, key is changed but does it really update Info.plist file?

**Comment by ismaeldcom** [comment]
Hi @jullienfall this module reads info.plist but you need to modify it manually. What do you want to achieve?

**Comment by jullienfall** [comment]
I need to add LSApplicationQueriesSchemes list dynamically received from BE

**Comment by ismaeldcom** [comment]
You can't add LSApplicationQueriesSchemes list dynamically because you need to add them before build. Maybe you can use a script to update it before build. What is BE?

**Comment by jullienfall** [comment]
backend

**Comment by jullienfall** [comment]
thanks!
