### ISSUE TITLE
Writing tests

### ISSUE THREAD

**Issue by nathanburgess** [ismaeldcom/react-native-build-config#15]
I'm unable to create a mock for this package. Is there a way to write tests to cover branches based off of values coming from this package?

**Comment by ismaeldcom** [comment]
Hi @nathanburgess can you share more information about your problem? Like what testing library are you using or some code.

**Comment by nathanburgess** [comment]
Actually wound up being able to mock this by adding `__mocks__/react-native-build-config.js`:
```js
const mockedBuildConfig = jest.genMockFromModule('react-native-build-config')

// mocked logic

export default mockedBuildConfig
```
