### ISSUE TITLE
Deprecation versions (failed to find target with hash string 'android-23')

### ISSUE THREAD

**Issue by askesis** [ismaeldcom/react-native-build-config#2]
Hi,  @ismaeldcom thanks for the package :)

I receive these warning, when I tried to start my project
![image](https://user-images.githubusercontent.com/23220242/51314700-734bad00-1a61-11e9-9bc4-a1e1463acc78.png)

I think that problem is with the versions into the android section in the `build.gradle` in your package
![image](https://user-images.githubusercontent.com/23220242/51314769-a2621e80-1a61-11e9-97a1-c763237c6bbe.png)

When I replace the `23` version on the `27` then everything works well

**Comment by ismaeldcom** [comment]
Thanks @askesis for the report, I just update it.
