### ISSUE TITLE
WARNING: Configuration 'compile' is obsolete

### ISSUE THREAD

**Issue by burtek** [ismaeldcom/react-native-build-config#5]
> \> Configure project :react-native-build-config
> WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
> It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

![image](https://user-images.githubusercontent.com/2940958/58452925-6d558f00-8119-11e9-86ff-a6d6b6c8b18e.png)

**Comment by ismaeldcom** [comment]
Solved in 3d76ba641d2819abd952bad8821e491be29a76ba

Thanks for report
