### ISSUE TITLE
BuildConfig information under 'default'

### ISSUE THREAD

**Issue by jnitecki** [ismaeldcom/react-native-build-config#9]
**BuildConfig information under 'default' element**

I have following code in my application
```
const BuildConfig = require('react-native-build-config');
console.log(BuildConfig.APPLICATION_ID);
console.log(BuildConfig.default.APPLICATION_ID);

```
As per documentation the line 'console.log(BuildConfig.APPLICATION_ID);' shall output APPLICATION_ID, but indeed the config variables appear as part of default object and only the second version console.log(BuildConfig.default.APPLICATION_ID); works.

This is new application build with ReactNative 0.60.4, in my old app (ReactNative 0.59.x) all seem to be working fine.

Any recomendation why it will happen?

**Comment by ismaeldcom** [comment]
Hi @jnitecki 

I've created a new project with RN 0.60.4 and using the following minimum code the result is the expected one.
```
import BuildConfig from 'react-native-build-config'
console.dir(BuildConfig)
```
![image](https://user-images.githubusercontent.com/7670276/62003966-59310c80-b11f-11e9-992f-4070cc2e162b.png)

I couldn't find any reference to your case on the net. Are you using the new autolink functionality?

**Comment by jnitecki** [comment]
I'm using autolink and autolinking works ok - at the end I'm getting object but with details under default property.

Intersting findings:
After adding log statements in react-native-build-config/lib/index.js like below:
```
// bridge to all the buildConfigField set in build.gradle and exported via RNBuildConfig
import { NativeModules } from 'react-native'
|const { RNBuildConfig } = NativeModules
console.log(RNBuildConfig);
console.log(RNBuildConfig.APPLICATION_ID); // returns correct value
export default RNBuildConfig;
```
The information is shown correctly there, but once this gets imported to my constants.js
```
const BuildConfig = require('react-native-build-config');
console.log(BuildConfig.APPLICATION_ID); // returns undefined
console.log(BuildConfig.default.APPLICATION_ID); // returns correct value
```
The value APPLICATION_ID appears under default property only.
Looks like some JavaScript magic which I cannot comprehend.

**Comment by ismaeldcom** [comment]
I think I know what the problem is.

The default "child" you obtain after the `require('react-native-build-config')` is because of the `export default RNBuildConfig;` of the lib.

If you require the lib using `import` without the `{}` like in my last example `import BuildConfig from 'react-native-build-config'` you obtain the default export.

What I don't know is why it only happens in this version. Maybe is a new config of transpilation by RN.

**Comment by jnitecki** [comment]
I can confirm that syntax with import works perfectly, while the one with require does not. My working app which is using require syntax is RN 0.59, so as you said maybe there is some issue with RN behavior. To be on safe side, it maybe useful to update Usage info of react-native-build-config
